import { db, type CompetitorRecord } from '../db';

const now = Date.now();
const DAY = 24 * 60 * 60 * 1000;

export const SEED_COMPETITORS: CompetitorRecord[] = [
  {
    id: 'comp_tattoogenda',
    name: 'Tattoogenda',
    website: 'https://tattoogenda.com',
    category: 'studio_mgmt',
    description: '纹身工作室专用全栈管理平台，支持多艺术家排期、数字同意书、EU墨水护照',
    features: [
      { name: '预约排期', notes: '24/7在线预约、多艺术家日历、缓存区管理', rating: 'best' },
      { name: '数字同意书', notes: '可定制同意书模板、拍照签名、合规存档', rating: 'best' },
      { name: 'POS收银', notes: '整合支付、押金管理、零售销售', rating: 'good' },
      { name: '库存管理', notes: '实时多地点库存同步、SKU追踪', rating: 'good' },
      { name: '客户管理', notes: '客户档案、预约历史、作品记录', rating: 'good' },
      { name: '营销获客', notes: '基础提醒邮件、短信提醒', rating: 'basic' },
    ],
    pricing: '免费版 ~ €45/mo',
    strengths: 'EU合规最完善(墨水护照)、数字化同意书行业标杆、多艺术家日历设计优秀',
    weaknesses: '北美市场覆盖弱、营销功能较基础',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 90 * DAY,
  },
  {
    id: 'comp_tattoostudiopro',
    name: 'Tattoo Studio Pro',
    website: 'https://tattoostudiopro.com',
    category: 'studio_mgmt',
    description: 'iOS+Web纹身工作室管理，4.0版新增角色权限、Stripe POS、库存追踪',
    features: [
      { name: '预约排期', notes: '队列仪表盘、自动提醒、角色权限', rating: 'good' },
      { name: '数字同意书', notes: '可定制健康问卷、同意书模板', rating: 'good' },
      { name: 'POS收银', notes: 'Stripe原生整合、服务+零售销售', rating: 'good' },
      { name: '库存管理', notes: '零售商品和耗材追踪', rating: 'basic' },
      { name: '客户管理', notes: '客户档案、作品集画廊', rating: 'good' },
      { name: '营销获客', notes: '基础提醒、评论管理', rating: 'basic' },
    ],
    pricing: '$29 ~ $119/mo',
    strengths: '30天免费试用、iOS原生体验好、Stripe整合深',
    weaknesses: 'Web端仍在beta、库存功能较浅、非多语言',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 80 * DAY,
  },
  {
    id: 'comp_studioflo',
    name: 'Studioflo',
    website: 'https://studioflo.io',
    category: 'studio_mgmt',
    description: 'AI驱动纹身工作室管理，免费版起，AI助手Athena处理客户沟通和预约',
    features: [
      { name: '预约排期', notes: 'AI辅助预约、离线Kiosk模式、多语言', rating: 'best' },
      { name: '数字同意书', notes: '自动化收集、条件逻辑、审计追踪', rating: 'best' },
      { name: 'POS收银', notes: '基础支付处理', rating: 'basic' },
      { name: '库存管理', notes: '基础追踪', rating: 'basic' },
      { name: '客户管理', notes: 'AI客户沟通、统一收件箱(W/A/IG/短信/邮件)', rating: 'best' },
      { name: '营销获客', notes: '社媒自动发布、AI获客分类', rating: 'best' },
    ],
    pricing: '免费版 ~ 付费版',
    strengths: 'AI功能最领先、免费版可用、统一收件箱整合最好、个性化售后跟进',
    weaknesses: 'POS和库存功能偏弱、较新平台',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 70 * DAY,
  },
  {
    id: 'comp_inkbusiness',
    name: 'INKbusiness',
    website: 'https://inkbusiness.app',
    category: 'marketing',
    description: '多渠聊天整合平台，将WA/IG/TikTok/Messenger/短信/邮件统一到一个收件箱',
    features: [
      { name: '预约排期', notes: '基础日历', rating: 'basic' },
      { name: '数字同意书', notes: '无', rating: 'missing' },
      { name: 'POS收银', notes: '在线支付', rating: 'basic' },
      { name: '库存管理', notes: '基础', rating: 'basic' },
      { name: '客户管理', notes: '多渠道聊天整合、营销面板', rating: 'best' },
      { name: '营销获客', notes: '多渠道获客、自动跟进、免费版起', rating: 'best' },
    ],
    pricing: '免费版 ~ $10/mo 起',
    strengths: '多渠整合是核心差异化、免费版性价比高、营销面板实用',
    weaknesses: '工作室管理功能弱(非全栈)、依赖第三方预约',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 60 * DAY,
  },
  {
    id: 'comp_zylu',
    name: 'Zylu',
    website: 'https://zylu.com',
    category: 'studio_mgmt',
    description: '多艺术家多地点管理，拖拽式排期、session级佣金自动计算',
    features: [
      { name: '预约排期', notes: '拖拽式日历、多地点、多渠提醒(SMS/邮件/WA)', rating: 'best' },
      { name: '数字同意书', notes: '有', rating: 'good' },
      { name: 'POS收银', notes: 'Session级佣金自动计算', rating: 'best' },
      { name: '库存管理', notes: '基础', rating: 'basic' },
      { name: '客户管理', notes: '客户档案、到访历史', rating: 'good' },
      { name: '营销获客', notes: '艺术家主导获客模式', rating: 'good' },
    ],
    pricing: '未公开',
    strengths: '佣金计算最精细、拖拽排期体验好、多地点支持',
    weaknesses: '定价不透明、营销功能不够丰富',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 50 * DAY,
  },
  {
    id: 'comp_tattoopro',
    name: 'TattooPro',
    website: 'https://tattoopro.com',
    category: 'studio_mgmt',
    description: '$149/mo全栈纹身管理，自动佣金、数字小费、声誉管理',
    features: [
      { name: '预约排期', notes: '排期管理、自动提醒', rating: 'good' },
      { name: '数字同意书', notes: '数字签名', rating: 'good' },
      { name: 'POS收银', notes: '分期付款、部分付款、数字小费', rating: 'best' },
      { name: '库存管理', notes: '内置库存', rating: 'good' },
      { name: '客户管理', notes: '360°销售报表、评论管理', rating: 'good' },
      { name: '营销获客', notes: '声誉管理、评论筛选', rating: 'good' },
    ],
    pricing: '$149/mo',
    strengths: '支付功能完善(分期/部分付款/小费)、报表强大、声誉管理',
    weaknesses: '价格偏高、无免费版、界面传统',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 40 * DAY,
  },
  {
    id: 'comp_inkbook',
    name: 'Inkbook',
    website: 'https://inkbook.com',
    category: 'studio_mgmt',
    description: 'POS+CRM一体化解决方案，针对高流量工作室优化',
    features: [
      { name: '预约排期', notes: '日历+提醒', rating: 'good' },
      { name: '数字同意书', notes: '有', rating: 'good' },
      { name: 'POS收银', notes: '完整POS', rating: 'best' },
      { name: '库存管理', notes: '有', rating: 'good' },
      { name: '客户管理', notes: 'CRM为主、高流量工作流', rating: 'best' },
      { name: '营销获客', notes: '基础', rating: 'basic' },
    ],
    pricing: '未公开',
    strengths: '高流量工作室优化、POS+CRM一体',
    weaknesses: '信息较少、营销弱',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 30 * DAY,
  },
  {
    id: 'comp_vagaro',
    name: 'Vagaro',
    website: 'https://vagaro.com',
    category: 'booking',
    description: '跨行业美业平台，221K+用户，4.7★，纹身品类重要玩家',
    features: [
      { name: '预约排期', notes: '24/7在线预约、自动提醒', rating: 'best' },
      { name: '数字同意书', notes: '有', rating: 'good' },
      { name: 'POS收银', notes: '完整POS', rating: 'best' },
      { name: '库存管理', notes: '有', rating: 'good' },
      { name: '客户管理', notes: '富客户档案、参考图、session笔记', rating: 'best' },
      { name: '营销获客', notes: '消费者市场/获客引擎', rating: 'best' },
    ],
    pricing: '~$28/mo 起',
    strengths: '用户量大、获客市场强、全功能覆盖、品牌认知度高',
    weaknesses: '非纹身专用(通用美业)、定制化受限',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 20 * DAY,
  },
  {
    id: 'comp_mangomint',
    name: 'Mangomint',
    website: 'https://mangomint.com',
    category: 'studio_mgmt',
    description: '高端美业SaaS，5+艺术家工作室首选，93%推荐率',
    features: [
      { name: '预约排期', notes: '自动化排期、作品库', rating: 'best' },
      { name: '数字同意书', notes: '有', rating: 'good' },
      { name: 'POS收银', notes: '完整POS', rating: 'good' },
      { name: '库存管理', notes: '有', rating: 'good' },
      { name: '客户管理', notes: '参考图+成品画廊', rating: 'good' },
      { name: '营销获客', notes: '自动化运营', rating: 'good' },
    ],
    pricing: '~$165/mo+',
    strengths: '高端定位、自动化极强、界面现代化、推荐率最高',
    weaknesses: '价格高、小工作室不适合',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now - 10 * DAY,
  },
  {
    id: 'comp_booksy',
    name: 'Booksy',
    website: 'https://booksy.com',
    category: 'booking',
    description: '移动优先预约平台，消费者市场获客功能强，低价定位',
    features: [
      { name: '预约排期', notes: '移动优先、市场获客', rating: 'best' },
      { name: '数字同意书', notes: '基础', rating: 'basic' },
      { name: 'POS收银', notes: '基础支付', rating: 'basic' },
      { name: '库存管理', notes: '无', rating: 'missing' },
      { name: '客户管理', notes: '基础客户档案', rating: 'basic' },
      { name: '营销获客', notes: '消费者市场发现引擎', rating: 'best' },
    ],
    pricing: '低价',
    strengths: '获客能力强(消费者市场)、移动体验好、价格低',
    weaknesses: '后台管理弱、非全栈、无库存',
    status: 'active',
    lastCheckedAt: now,
    nextCheckAt: now + 30 * DAY,
    createdAt: now,
  },
];

export const MARKET_CHECK_KEY = 'inkflow_last_market_check';

export function getDaysSinceLastMarketCheck(): number {
  const last = localStorage.getItem(MARKET_CHECK_KEY);
  if (!last) return 999;
  return Math.floor((Date.now() - Number(last)) / (24 * 60 * 60 * 1000));
}

export function recordMarketCheck() {
  localStorage.setItem(MARKET_CHECK_KEY, String(Date.now()));
}

export async function seedCompetitorsIfEmpty(): Promise<void> {
  const count = await db.competitors.count();
  if (count === 0) {
    await db.competitors.bulkAdd(SEED_COMPETITORS);
  }
}
