// Script to automatically convert scraped data → cities.js
// Run: node scripts/update-cities.js
// Input: CSV from Harvests scraper
// Output: Updated marketing/src/lib/cities.js

import { readFileSync, writeFileSync } from 'fs';

// Paths - adjust based on your setup
const INPUT_CSV = 'F:/inkflow app/InkFlow_Project/inkflow_harvests/data/scrape_output/WA_Live_Scrape_View.csv';
const OUTPUT_JS = 'D:/ink-flow-manager/marketing/src/lib/cities.js';

function parseCSVLine(line) {
  const parts = line.split(',');
  return {
    city: parts[0]?.trim(),
    name: parts[1]?.trim(),
    rating: parseFloat(parts[2]) || 0,
    reviews: parseInt(parts[3]) || 0,
    phone: parts[4]?.trim(),
    address: parts[5]?.trim(),
  };
}

function generateCitiesJS(shops) {
  // Group shops by city
  const cityMap = {};
  for (const shop of shops) {
    const city = shop.city?.toLowerCase().replace(/[^a-z]/g, '-');
    if (!cityMap[city]) cityMap[city] = { name: shop.city, shops: [] };
    cityMap[city].shops.push(shop);
  }

  // Generate cities.js content
  let output = `// Auto-generated by update-cities.js\n`;
  output += `export const cities = [\n`;
  for (const [slug, data] of Object.entries(cityMap)) {
    output += `  { slug: '${slug}', name: '${data.name}', state: 'WA', country: 'us',\n`;
    output += `    shops: [\n`;
    for (const shop of data.shops) {
      output += `      { name: '${shop.name.replace(/'/g, "\\'")}', rating: ${shop.rating}, reviews: ${shop.reviews}, phone: '${shop.phone}', address: '${shop.address.replace(/'/g, "\\'")}', local: true },\n`;
    }
    output += `    ],\n`;
    output += `    nearby: [],\n`;
    output += `  },\n`;
  }
  output += `];\n`;
  output += `export const aftercareProducts = [];\n`;

  return output;
}

// Main
try {
  const csv = readFileSync(INPUT_CSV, 'utf-8');
  const lines = csv.split('\n').filter(l => l.trim());
  const shops = lines.slice(1).map(parseCSVLine); // skip header
  const js = generateCitiesJS(shops);
  writeFileSync(OUTPUT_JS, js, 'utf-8');
  console.log(`Generated ${Object.keys(shops).length} cities → ${OUTPUT_JS}`);
} catch (e) {
  console.error('Error:', e.message);
}
